#类型名称，注释

#
null_action,both,0,无效动作,STATUS_NEVER,False

#
ping_pong,both,1,测试连接状态,STATUS_NEVER,False

#
forced_into,c2s,2,踢掉在线的准备强制登陆,STATUS_NEVER,False

#
get_session,c2s,3,获得Session对象,STATUS_NEVER,False
	sessionkey,String,False,
	account,String,False,玩家id
	version,String,False,版本
