#类型名称，注释

#
NullAction,external,0,无效动作,STATUS_NEVER,False

#
PingPong,external,1,测试连接状态,STATUS_NEVER,False

#
ServerRegOpcode,internal,2,服务器注册消息号,STATUS_NEVER,False
	opcodes,int,True,消息号
	
#
ServerRegIdentity,internal,3,服务器注册身份信息,STATUS_NEVER,False
	identity,byte,False,身份信息

#
GetSession,external,4,获得Session对象,STATUS_NEVER,False
	fd,int,False,客户端连接网关服的fd
	sessionkey,String,False,会话密钥
	
#
CreateConnection,internal,5,客户端连接进来了,STATUS_NEVER,False
	fd,int,False,客户端连接网关服的fd
	remoteIp,String,False,客户端ip
	remotePort,short,False,客户端网关

#
OperationResult,external,6,操作结果,STATUS_NEVER,False
	type,short,False,操作类型
	reason,short,False,造成结果的原因
	data,String,False,参数

#
DestroyConnection,internal,7,销毁fd,STATUS_NEVER,False
	fd,int,False,客户端连接网关服的fd
	
#
CreateChar,external,10,创建角色,STATUS_NEVER,False
	charData,CharCreateInfo,False,角色信息

#
IdentityServerMsg,internal,11,通知服务器身份,STATUS_NEVER,False
	serverType,int,False,服务器身份
	
#
ServerStartFinishMsg,internal,12,通知网关服启动完成,STATUS_NEVER,False
	bootstrap,boolean,False,启动状态

#
InstanceResult,external,375,副本结果,STATUS_NEVER,False
	state,byte,False,副本状态(249:副本失败 250:副本通关 251:副本未通关)
	cd,byte,False,副本cd
	list,ItemRewardInfo,True,道具列表
	type,byte,False,副本类型
	data,String,False,额外数据
	